server:
  port: 9000

spring:
  application:
    name: cards
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:cardsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
#    url: jdbc:postgresql://localhost:5436/cardsdb
#    username: root
#    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: cards
    description: "Trust Wave Bank Cards Microservice"
    version: "1.0.0"
logging:
  level:
    com:
      trustwave:
        cards: DEBUG
  pattern:
    console: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
