
services:
  accounts:
    image: "harshaldev55/accounts:v1"
    container_name: accounts-ms
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - trustwave
  loans:
    image: "harshaldev55/loans:latest"
    container_name: loans-ms
    ports:
      - "9003:9003"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - trustwave
  cards:
    image: "harshaldev55/cards:latest"
    container_name: cards-ms
    ports:
      - "9002:9002"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - trustwave

networks:
  trustwave:
    driver: "bridge"