spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: api-gateway
    description: "Trust Wave Bank API GateWay Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      trustwave:
        apigateway: DEBUG
