spring:
  application:
    name: api-gateway
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 30000
            response-timeout: 10s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: api-gateway
    description: "Trust Wave Bank API GateWay Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      trustwave:
        apigateway: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p){red=ERROR,yellow=WARN,green=INFO,blue=DEBUG,magenta=TRACE} %clr([${spring.application.name:config-server}]){cyan} %clr([%X{traceId:-},%X{spanId:-}]){yellow} %clr(%logger{36}){blue} %clr(:){faint} %m%n"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
