
services:
#  accountsdb:
#    container_name: accountsdb
#    ports:
#      - "5434:5432"
#    environment:
#      POSTGRES_DB: accountsdb
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U root -d accountsdb"]
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  loansdb:
#    container_name: loansdb
#    ports:
#      - "5435:5432"
#    environment:
#      POSTGRES_DB: loansdb
#    healthcheck:
#        test: ["CMD-SHELL", "pg_isready -U root -d loansdb"]
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
#
#  cardsdb:
#    container_name: cardsdb
#    ports:
#      - "5436:5432"
#    environment:
#      POSTGRES_DB: cardsdb
#    healthcheck:
#        test: ["CMD-SHELL", "pg_isready -U root -d cardsdb"]
#    extends:
#      file: common-config.yml
#      service: microservice-db-config

#  rabbit:
#    image: rabbitmq:4-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: "rabbitmq-diagnostics check_port_connectivity"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: "harshaldev55/config-server:v1"
    container_name: config-server-ms
    ports:
      - "8071:8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eureka-discovery-server:
    image: "harshaldev55/eureka-discovery-server:v1"
    container_name: eureka-discovery-server-ms
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-config-server-config
    environment:
      SPRING_APPLICATION_NAME: "eureka-discovery-server"

  accounts:
    image: "harshaldev55/accounts:v1"
    container_name: accounts-ms
    ports:
      - "9001:9001"
    depends_on:
      config-server:
        condition: service_healthy
#      accountsdb:
#        condition: service_healthy
      eureka-discovery-server:
       condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9001/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: accounts
#      SPRING_DATASOURCE_URL: jdbc:postgresql://accountsdb:5432/accountsdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "harshaldev55/loans:v1"
    container_name: loans-ms
    ports:
      - "9003:9003"
    depends_on:
      config-server:
        condition: service_healthy
#      loansdb:
#        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9003/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: loans
#      SPRING_DATASOURCE_URL: jdbc:postgresql://loansdb:5432/loansdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "harshaldev55/cards:v1"
    container_name: cards-ms
    ports:
      - "9002:9002"
    depends_on:
      config-server:
        condition: service_healthy
#      cardsdb:
#        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9002/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: cards
#      SPRING_DATASOURCE_URL: jdbc:postgresql://cardsdb:5432/cardsdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  api-gateway:
    image: "harshaldev55/api-gateway:v1"
    container_name: api-gateway-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  trustwave:
    driver: "bridge"