services:
  network-deploy-service:
    networks:
      - trustwave

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: "postgres:latest"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  microservice-base-config:
    extends:
      service: network-deploy-service
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none


  microservice-config-server-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 12345

  microservice-eureka-config:
    extends:
      service: microservice-config-server-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-discovery-server:8070/eureka/"
