server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/harshal5-dev/trust-wave-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//shraddha-harshal//config"
