server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
        #search-locations: "classpath:/config"
        #search-locations: "file:///Users//shraddha-harshal//config"
        git:
          uri: "https://github.com/harshal5-dev/trust-wave-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: "e9f3b8b6a5d4719f8473c23f2de0a62c09c59d1f627e4e97fbbc2d1f82e9cba1"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      trustwave:
        configserver: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p){red=ERROR,yellow=WARN,green=INFO,blue=DEBUG,magenta=TRACE} %clr([${spring.application.name:config-server}]){cyan} %clr([%X{traceId:-},%X{spanId:-}]){yellow} %clr(%logger{36}){blue} %clr(:){faint} %m%n"
