server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
        #search-locations: "classpath:/config"
        #search-locations: "file:///Users//shraddha-harshal//config"
        git:
          uri: "https://github.com/harshal5-dev/trust-wave-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: "e9f3b8b6a5d4719f8473c23f2de0a62c09c59d1f627e4e97fbbc2d1f82e9cba1"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true