services:
  network-deploy-service:
    networks:
      - trustwave

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: "postgres:latest"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  microservice-base-config:
    extends:
      service: network-deploy-service
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-config-server-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345